//TODO labels
export const WORKFLOW_PLACES = {
  KONCEPT: 'KONCEPT',
  K_PREPRACOVANI: 'K_PREPRACOVANI',
  STORNO: 'STORNO',

  KE_SCHVALENI_B: 'KE_SCHVALENI_B',
  KE_SCHVALENI_KRAJ: 'KE_SCHVALENI_KRAJ',
  PRIPRAVA_K_PODPISU: 'PRIPRAVA_K_PODPISU',

  PRIPRAVA_DAVKY: 'PRIPRAVA_DAVKY',
  KE_SCHVALENI_KRAJ_DAVKA: 'KE_SCHVALENI_KRAJ_DAVKA',
  PRIPRAVA_K_PODPISU_DAVKA: 'PRIPRAVA_K_PODPISU_DAVKA',

  K_PODPISU_B: 'K_PODPISU_B',
  K_VALIDACI_PODPISU_B: 'K_VALIDACI_PODPISU_B',
  NEVALIDNI_PODPIS_B: 'NEVALIDNI_PODPIS_B',

  KE_KONTROLE_GINIS: 'KE_KONTROLE_GINIS',
  KE_KONTROLE_ROPID: 'KE_KONTROLE_ROPID',

  K_PODPISU_ROPID: 'K_PODPISU_ROPID',
  K_VALIDACI_PODPISU_ROPID: 'K_VALIDACI_PODPISU_ROPID',
  NEVALIDNI_PODPIS_ROPID: 'NEVALIDNI_PODPIS_ROPID',

  K_PODPISU_A: 'K_PODPISU_A',
  K_VALIDACI_PODPISU_A: 'K_VALIDACI_PODPISU_A',
  NEVALIDNI_PODPIS_A: 'NEVALIDNI_PODPIS_A',

  KONEC_PODEPISOVANI_SMLOUVY: 'KONEC_PODEPISOVANI_SMLOUVY',
  KONTROLA_PRED_VYRIZENIM: 'KONTROLA_PRED_VYRIZENIM',
  VYRIZENO: 'VYRIZENO',
}

export const WORKFLOW_PLACES_BATCH = {
  PRIPRAVA: 'PRIPRAVA',
  ODESLANO: 'ODESLANO',
  ZPRACOVANI: 'ZPRACOVANI',
  VYRIZENO: 'VYRIZENO',
}

//TODO labels
export const workwlowPlaceOptions = Object.keys(WORKFLOW_PLACES).map((code) => ({ label: code, value: code }))
export const workwlowPlaceBatchOptions = Object.keys(WORKFLOW_PLACES_BATCH).map((code) => ({
  label: code,
  value: code,
}))

export const SIGN_TRANSITIONS = {
  [WORKFLOW_PLACES.K_PODPISU_A]: WORKFLOW_PLACES.K_VALIDACI_PODPISU_A,
  [WORKFLOW_PLACES.K_PODPISU_B]: WORKFLOW_PLACES.K_VALIDACI_PODPISU_B,
  [WORKFLOW_PLACES.K_PODPISU_ROPID]: WORKFLOW_PLACES.K_VALIDACI_PODPISU_ROPID,
}
